apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sops
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: infra
  source:
    repoURL: https://github.com/Slowbro213/homelab.git
    targetRevision: main
    path: apps/argocd-sops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
