apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno-policies
    targetRevision: 3.8.0
    helm:
      releaseName: kyverno-policies
      values: |
        podSecurityStandard: restricted
        validationFailureAction: Enforce
        validationAllowExistingViolations: false
        validationFailureActionOverrides:
          all:
            - action: Audit
              namespaces:
                - kube-system
                - longhorn-system
                - tailscale
        policyExclude:
          disallow-capabilities-strict:
            any:
              - resources:
                  kinds:
                    - Job
                    - Pod
                  namespaces:
                    - minio
                  names:
                    - minio-post-job*
          disallow-privilege-escalation:
            any:
              - resources:
                  kinds:
                    - Job
                    - Pod
                  namespaces:
                    - minio
                  names:
                    - minio-post-job*
          disallow-host-namespaces:
            any:
              - resources:
                  kinds:
                    - DaemonSet
                    - Pod
                  namespaces:
                    - monitoring
                  names:
                    - monitoring-prometheus-node-exporter*
          disallow-host-path:
            any:
              - resources:
                  kinds:
                    - DaemonSet
                    - Pod
                  namespaces:
                    - monitoring
                  names:
                    - monitoring-prometheus-node-exporter*
          restrict-volume-types:
            any:
              - resources:
                  kinds:
                    - DaemonSet
                    - Pod
                  namespaces:
                    - monitoring
                  names:
                    - monitoring-prometheus-node-exporter*
        background: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
