apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
spec:
  project: infra

  source:
    repoURL: https://charts.jetstack.io
    chart: trust-manager
    targetRevision: v0.19.0
    helm:
      releaseName: trust-manager
      valuesObject:
        app:
          trust:
            namespace: cert-manager
        secretTargets:
          enabled: true
          authorizedSecrets:
            - gentoo-internal-ca-bundle

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
