apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.32.0
    helm:
      releaseName: vault
      valuesObject:
        injector:
          securityContext:
            pod:
              runAsNonRoot: true
              runAsGroup: 1000
              runAsUser: 100
              fsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
            container:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

          statefulSet:
            securityContext:
              pod:
                runAsNonRoot: true
                runAsGroup: 1000
                runAsUser: 100
                fsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              container:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault

          ha:
            enabled: true
            replicas: 2
            raft:
              enabled: true
              setNodeId: true

          dataStorage:
            enabled: true
            storageClass: longhorn-rwo
            size: 10Gi

          auditStorage:
            enabled: true
            storageClass: longhorn-rwo

        ui:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
