apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.32.0
    helm:
      releaseName: vault
      valuesObject:
        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true

          dataStorage:
            enabled: true
            storageClass: longhorn-rwo
            size: 10Gi

          auditStorage:
            enabled: true
            storageClass: longhorn-rwo

        ui:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
