apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  source:
    repoURL: http://zotregistry.dev/helm-charts/
    chart: zot
    targetRevision: 0.1.112
    helm:
      releaseName: zot
      valuesObject:
        mountConfig: true
        podSecurityContext:
          fsGroup: 10001
          runAsGroup: 10001
          runAsUser: 10001
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        configFiles:
          config.json: |
            {
              "storage": {
                "rootDirectory": "/var/lib/registry",
                "dedupe": false,
                "storageDriver": {
                  "name": "s3",
                  "region": "us-east-1",
                  "regionendpoint": "http://minio.minio.svc.cluster.local:9000",
                  "bucket": "zot",
                  "secure": false,
                  "forcepathstyle": true
                }
              },
              "http": {
                "address": "0.0.0.0",
                "port": "5000"
              },
              "log": {
                "level": "debug"
              }
            }

        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: zot-s3-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: zot-s3-credentials
                key: AWS_SECRET_ACCESS_KEY

        service:
          type: ClusterIP
          port: 5000

        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: registry.gentoo.lan
              paths:
                - path: /
                  pathType: Prefix

  destination:
    server: https://kubernetes.default.svc
    namespace: registry

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
