apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  gentoo-lan.server: |
    gentoo.lan:53 {
      errors
      cache 30
      hosts {
        10.43.187.55 sso.gentoo.lan
        10.43.187.55 git.gentoo.lan
        10.43.187.55 registry.gentoo.lan
        fallthrough
      }
    }
  tailnet.server: |
    tail27527e.ts.net:53 {
      errors
      cache 30
      forward . 100.100.100.100
    }
