apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - coredns-custom.yaml
  - kyverno-policies.yaml
  - network-policies/apps.yaml
  - network-policies/cert-manager.yaml
  - network-policies/logging.yaml
  - network-policies/minio.yaml
  - network-policies/monitoring.yaml
  - network-policies/registry.yaml
  - network-policies/redis.yaml
  - network-policies/nats.yaml
  - network-policies/vault.yaml
  - network-policies/vault-secrets-operator.yaml
  - network-policies/longhorn.yaml
  - network-policies/databases.yaml
  - network-policies/falco.yaml
  - network-policies/smartctl-exporter.yaml
  - network-policies/gitea.yaml
  - network-policies/gitea-runners.yaml
  - network-policies/authentik.yaml
  - network-policies/cloudflare.yaml
  - network-policies/cloudflare-friend.yaml
  - network-policies/velero.yaml
  - resource-limits/cntdwn.yaml
  - resource-limits/programmingclub.yaml
  - resource-limits/whoami.yaml
  - resource-limits/velero.yaml
