apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: gentoo-internal-ca-bundle
spec:
  sources:
    - secret:
        name: gentoo-internal-ca
        key: ca.crt
  target:
    namespaceSelector:
      matchLabels:
        trust.gentoo.lan/internal-ca: "true"
    secret:
      key: ca.crt
      metadata:
        labels:
          trust.gentoo.lan/bundle: internal-ca
