apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: REPLACE_APP_NAME
  namespace: argocd
  labels:
    image-updater.gentoo.lan/enabled: "true"
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=registry.gentoo.lan/frontends/REPLACE_REPO:main
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-gitea
    argocd-image-updater.argoproj.io/git-repository: http://gitea-http.gitea.svc.cluster.local:3000/REPLACE_OWNER/REPLACE_REPO.git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: frontends
  source:
    repoURL: https://git.thanaspapa.com/REPLACE_OWNER/REPLACE_REPO.git
    targetRevision: main
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: REPLACE_NAMESPACE
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
