# apps/authentik/values.yaml

authentik:
  enabled: true
  existingSecret:
    secretName: authentik-config

postgresql:
  enabled: false

global:
  env:
    - name: AUTHENTIK_LOG_LEVEL
      value: info

    - name: AUTHENTIK_POSTGRESQL__HOST
      value: postgres-ha-rw.databases.svc.cluster.local
    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__SSLMODE
      value: disable

server:
  replicas: 1

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations: {}
    hosts:
      - sso.gentoo.lan
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: authentik-internal-tls
        hosts:
          - sso.gentoo.lan

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

worker:
  replicas: 1

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

prometheus:
  rules:
    enabled: false
