apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none
  policy.csv: |
    p, role:none, applications, get, */*, deny
    p, role:none, applications, sync, */*, deny
    p, role:none, applications, action/*, */*, deny
    p, role:none, logs, get, */*, deny
    p, role:none, exec, create, */*, deny
