apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age
          secret:
            secretName: sops-age
        - name: kustomize-plugin
          emptyDir: {}

      initContainers:
        - name: install-sops-ksops
          image: viaductoss/ksops:v4.3.3
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -eu

              echo "Installing ksops and kustomize..."
              install -m 0755 ksops /custom-tools/ksops
              install -m 0755 kustomize /custom-tools/kustomize
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: custom-tools
              mountPath: /custom-tools

      containers:
        - name: argocd-repo-server
          env:
            - name: XDG_CONFIG_HOME
              value: /home/argocd/.config
            - name: SOPS_AGE_KEY_FILE
              value: /home/argocd/.config/sops/age/keys.txt
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
          volumeMounts:
            - name: custom-tools
              mountPath: /usr/local/bin/ksops
              subPath: ksops
            - name: custom-tools
              mountPath: /usr/local/bin/kustomize
              subPath: kustomize
            - name: sops-age
              mountPath: /home/argocd/.config/sops/age
              readOnly: true
