apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# snapshot-controller upstream deploys into kube-system.
resources:
  - crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  - crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  - crds/snapshot.storage.k8s.io_volumesnapshots.yaml
  - controller/rbac-snapshot-controller.yaml
  - controller/setup-snapshot-controller.yaml
  - volumesnapshotclass.yaml
