apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-servers
  namespace: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "postgres-ha",
          "Group": "Homelab",
          "Host": "postgres-ha-rw.databases.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "postgres",
          "Username": "pgadmin",
          "ConnectionParameters": {
            "sslmode": "verify-full",
            "sslrootcert": "/etc/ssl/gentoo/ca.crt",
            "connect_timeout": 10
          }
        }
      }
    }
