apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:Fu4Zsls=,iv:2LxauRkZoBbYpYcdmd+EsDltwKA1pfnduVpPwAU3sVw=,tag:Oxz3co2EI7zZL3ZV9/JGrA==,type:str]
    admin-password: ENC[AES256_GCM,data:m014h7oXRNo=,iv:vAxM7+0d07J9LYoFrYzq98dWw75ypB3iWqcd/FwHYWg=,tag:a0o63gTnfq0CpMS+wPLAVA==,type:str]
sops:
    age:
        - recipient: age12lk6x3ugvxxmst4dvtpfc6mwjazr6ayrth000rtfe9uc4lyrjduqx62tfs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTXZYMHZUMDZIRkF3QXQw
            MWp1YXBDTUMwMVlkcU94NlZ6SG8zakxoWm5nCjhXTGxHQ2ROeVR5cXVQenFtQ1ht
            TFlmdUVuYkRTWnVySXh5dnNXWUJHS3cKLS0tIHdrb1BCNm1PWlJLbityTkJBZXUv
            UGpnQm85aFlVMXl4QlU1UGVMS2pLWmsKkb4c6x6BBwTJ5to8QvSHSu+go2QSkwJY
            iur7E4QxLyxorWDoy0P2AzQJ2z3fMuqmj6Re+CIGWpgH1juxUgfyFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T07:59:00Z"
    mac: ENC[AES256_GCM,data:4Gsdl3LKriAsTtH3G17gnK3gpVlU9mGLrqSXYcmrcSqXUXQmTHNGRq6eUTR5D5cgast+sNnTOJcn30gMjUJm21mTyythsLS6jb1ArMnpRugzs3WF/mYbL8BAecC/0khMN2AgkwdwAsNz9wzBn0BZKPyN+KE+r1ZimUnKPZuqNO8=,iv:sRBlpL5DXJXiKUsBIAZEL+SVzHw2+SGv9qZumf+4URw=,tag:3vs8TD9BzljemfONwbp1og==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
