apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-16"
spec:
  project: infra

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-agent-injector-cfg
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.32.0
    helm:
      releaseName: vault
      valuesObject:
        global:
          tlsDisable: false

        injector:
          securityContext:
            pod:
              runAsNonRoot: true
              runAsGroup: 1000
              runAsUser: 100
              fsGroup: 1000
              seccompProfile:
                type: RuntimeDefault
            container:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              seccompProfile:
                type: RuntimeDefault

        server:
          affinity: ""

          volumes:
            - name: vault-internal-tls
              secret:
                secretName: vault-internal-tls

          volumeMounts:
            - name: vault-internal-tls
              mountPath: /vault/userconfig/vault-internal-tls
              readOnly: true

          statefulSet:
            securityContext:
              pod:
                runAsNonRoot: true
                runAsGroup: 1000
                runAsUser: 100
                fsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              container:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault

          ha:
            enabled: true
            replicas: 2
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true

                listener "tcp" {
                  tls_disable = 0
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_cert_file = "/vault/userconfig/vault-internal-tls/tls.crt"
                  tls_key_file = "/vault/userconfig/vault-internal-tls/tls.key"
                  tls_client_ca_file = "/vault/userconfig/vault-internal-tls/ca.crt"
                }

                storage "raft" {
                  path = "/vault/data"
                }

                service_registration "kubernetes" {}

          dataStorage:
            enabled: true
            storageClass: longhorn-rwo
            size: 10Gi

          auditStorage:
            enabled: true
            storageClass: longhorn-rwo

        ui:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
