apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cntdwn
  namespace: argocd
  labels:
    image-updater.gentoo.lan/enabled: "true"
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=registry.gentoo.lan/frontends/cntdwn:main
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-gitea
    argocd-image-updater.argoproj.io/git-repository: http://gitea-http.gitea.svc.cluster.local:3000/thanas-papa/cntdwn.git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: frontends

  source:
    repoURL: https://git.thanaspapa.com/thanas-papa/cntdwn.git
    targetRevision: main
    path: deploy/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: cntdwn

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
