apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Slowbro213/homelab.git
    targetRevision: main
    path: apps/grafana-secrets
    kustomize:
      buildOptions: --enable-alpha-plugins --enable-exec
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
