apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://github.com/Slowbro213/homelab.git
    targetRevision: main
    path: apps/minio-tailscale
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
