apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: programmingclub
  namespace: argocd
spec:
  project: frontends

  source:
    repoURL: https://git.thanaspapa.com/thanas-papa/programmingclub.git
    targetRevision: main
    path: deploy/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: programmingclub

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
