apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gentoo-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  sourceRepos:
    - https://github.com/Slowbro213/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: AppProject
    - group: argoproj.io
      kind: Application
    - group: kyverno.io
      kind: ClusterPolicy
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: ""
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  sourceRepos:
    - https://charts.longhorn.io/
    - https://charts.min.io/
    - https://grafana.github.io/helm-charts
    - https://helm.releases.hashicorp.com
    - https://kyverno.github.io/kyverno
    - https://pkgs.tailscale.com/helmcharts
    - http://zotregistry.dev/helm-charts/
    - https://prometheus-community.github.io/helm-charts
    - https://github.com/Slowbro213/homelab.git
    - https://cloudnative-pg.github.io/charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: kyverno
    - server: https://kubernetes.default.svc
      namespace: longhorn-system
    - server: https://kubernetes.default.svc
      namespace: tailscale
    - server: https://kubernetes.default.svc
      namespace: vault
    - server: https://kubernetes.default.svc
      namespace: vault-secrets-operator
    - server: https://kubernetes.default.svc
      namespace: minio
    - server: https://kubernetes.default.svc
      namespace: registry
    - server: https://kubernetes.default.svc
      namespace: logging
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: cnpg-system
    - server: https://kubernetes.default.svc
      namespace: databases 
    - server: https://kubernetes.default.svc
      namespace: kube-system
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  sourceRepos:
    - https://github.com/Slowbro213/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: apps
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  sourceRepos:
    - https://github.com/Slowbro213/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: kyverno.io
      kind: ClusterPolicy
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ServiceAccount
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: secrets.hashicorp.com
      kind: VaultAuth
    - group: secrets.hashicorp.com
      kind: VaultConnection
    - group: secrets.hashicorp.com
      kind: VaultStaticSecret
