apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-tailscale
  namespace: vault
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: vault
      port:
        name: https
  tls:
    - hosts:
        - vault-vault-tailscale
