apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-rule-alertmanager-test.yaml
  - prometheus-rule-node-health.yaml
  - alertmanagerconfig-discord.yaml
  - grafana-dashboard-node-health.yaml
  - servicemonitor-smartctl-exporter.yaml
