apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartctl-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - smartctl-exporter
  selector:
    matchLabels:
      app.kubernetes.io/name: smartctl-exporter
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
          action: replace
