apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: cert-manager
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: monitoring
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: minio
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: logging
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: registry
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
--- 
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: databases
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: redis
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
--- 
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: authentik
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault
  namespace: cloudflare
spec:
  address: https://vault.vault.svc.cluster.local:8200
  caCertSecretRef: gentoo-internal-ca-bundle
  tlsServerName: vault.vault.svc.cluster.local

