apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: minio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: databases
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: redis
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: monitoring
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: monitoring
    serviceAccount: vault-sync
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: minio
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: minio
    serviceAccount: vault-sync
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: logging
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: logging
    serviceAccount: vault-sync
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: registry
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: registry
    serviceAccount: vault-sync
--- 
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: databases
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: postgres
    serviceAccount: vault-sync
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault
  namespace: redis
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: redis
    serviceAccount: vault-sync
