FROM oven/bun:1.2.20-alpine AS build
WORKDIR /src
COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM nginxinc/nginx-unprivileged:1.29.0-alpine
COPY --from=build /src/dist /usr/share/nginx/html
EXPOSE 8080
