apiVersion: v1
kind: LimitRange
metadata:
  name: velero-defaults
  namespace: velero
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
