apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smartctl-exporter
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: smartctl-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartctl-exporter
    spec:
      automountServiceAccountToken: false
      containers:
        - name: smartctl-exporter
          image: docker.io/prometheuscommunity/smartctl-exporter:v0.14.0
          args:
            - --smartctl.device=/dev/monitored-disk;nvme
            - --smartctl.device=/dev/monitored-disk;sat
          securityContext:
            privileged: true
            runAsUser: 0
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: metrics
              containerPort: 9633
          volumeMounts:
            - name: monitored-disk
              mountPath: /dev/monitored-disk
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
      volumes:
        - name: monitored-disk
          hostPath:
            path: /dev/monitored-disk
            type: BlockDevice
