apiVersion: v1
kind: Service
metadata:
  name: smartctl-exporter
  labels:
    app.kubernetes.io/name: smartctl-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smartctl-exporter
  ports:
    - name: metrics
      port: 9633
      targetPort: metrics
