apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tailscale
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/Slowbro213/homelab.git
    targetRevision: main
    path: apps/tailscale/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
