architecture: standalone

image:
  registry: docker.io
  repository: bitnamisecure/redis
  tag: ""
  digest: sha256:1347d526ecec0c6537e99eac09e7c3405c21664f6044ff60e78b0898da37abd2
  pullPolicy: IfNotPresent

auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretPasswordKey: password

master:
  persistence:
    enabled: true
    storageClass: longhorn-rwo
    size: 2Gi
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      memory: 512Mi

replica:
  replicaCount: 0

metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamisecure/redis-exporter
    tag: ""
    digest: sha256:839260c04bc3858980157da2f69219681bdcd8874fdb0a58c40b396050b5100d
    pullPolicy: IfNotPresent
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 30s
    labels:
      release: monitoring
