apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: object-storage-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./object-storage.enc.yaml
