apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-public-readonly
  namespace: gitea
spec:
  ingressClassName: traefik
  rules:
    - host: git.thanaspapa.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-public-readonly-proxy
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-internal-admin
  namespace: gitea
  annotations:
    cert-manager.io/cluster-issuer: gentoo-internal-ca
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - git.gentoo.lan
      secretName: git-gentoo-lan-tls
  rules:
    - host: git.gentoo.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea-http
                port:
                  number: 3000
